name: Upload resource pack to mc-packs.net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  upload-resource-pack:
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get update && sudo apt-get -y install zip

      - name: Zip contents of repository
        run: |
          zip -r craftville.zip .
          mv craftville.zip $GITHUB_WORKSPACE

      - name: Upload resource pack to https://mc-packs.net/
        id: upload
        run: |
          curl -X POST -F "file=@craftville.zip" https://mc-packs.net/
        shell: bash

      - name: Get resource pack URL
        run: |
          echo "::set-output name=url::$(echo ${{steps.upload.outputs.stdout}} | sed 's/^.*download/https:\/\/mc-packs.net\/download/')"
        id: get-url
        shell: bash

      - name: Send Discord webhook
        uses: MineBartekSA/discord-webhook@v2.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Resource pack uploaded: ${{ steps.get-url.outputs.url }}'
          username: 'Resource pack'
